
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 23 05:36:29 CDT 2018
//----------------------------------------------------

package fes.aragon.archivos;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int pyc = 20;
  public static final int rep = 8;
  public static final int parIzq = 10;
  public static final int movAb = 5;
  public static final int NoParArr = 16;
  public static final int parDer = 11;
  public static final int llaveIzq = 21;
  public static final int llaveDer = 22;
  public static final int NoParIzq = 14;
  public static final int num = 25;
  public static final int NoParDer = 15;
  public static final int pareIzq = 23;
  public static final int inicio = 18;
  public static final int NoParAb = 17;
  public static final int pareDer = 24;
  public static final int EOF = 0;
  public static final int parAb = 13;
  public static final int error = 1;
  public static final int mient = 9;
  public static final int movArr = 4;
  public static final int fin = 19;
  public static final int comer = 6;
  public static final int parArr = 12;
  public static final int si = 7;
  public static final int movIzq = 2;
  public static final int movDer = 3;
}

