/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fes.aragon.programas;

import fes.aragon.Seleccion;
import fes.aragon.archivos.jflex2.Lexico;
import fes.aragon.archivos.jflex2.Tokens;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Axel
 */
public class JFlex2 extends javax.swing.JFrame {
    private Seleccion ventanaSeleccion;
    
    private File archivo;

    /**
     * Creates new form JFlex2
     */
    public JFlex2(Seleccion ventanaAnterior) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.ventanaSeleccion = ventanaAnterior;
        txtRuta.setText(System.getProperty("user.dir") + "\\JFlex 2\\Fuente.txt");
        archivo = new File(txtRuta.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAtras = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnReglas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        btnSeleccionar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRuta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        btnVerFuente = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taSalida = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrar.setBackground(new java.awt.Color(0, 153, 153));
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fes/aragon/imagenes/Cerrar.png"))); // NOI18N
        lblCerrar.setToolTipText("Cerrar");
        lblCerrar.setOpaque(true);
        lblCerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCerrarMouseMoved(evt);
            }
        });
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
        });
        jPanel1.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        lblMinimizar.setBackground(new java.awt.Color(0, 153, 153));
        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fes/aragon/imagenes/Minimizar.png"))); // NOI18N
        lblMinimizar.setToolTipText("Minimizar");
        lblMinimizar.setOpaque(true);
        lblMinimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseMoved(evt);
            }
        });
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseExited(evt);
            }
        });
        jPanel1.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel5.setText("Programa 7: JFlex 2");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, 20));

        lblAtras.setBackground(new java.awt.Color(0, 153, 153));
        lblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fes/aragon/imagenes/atras.png"))); // NOI18N
        lblAtras.setToolTipText("Atrás");
        lblAtras.setOpaque(true);
        lblAtras.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblAtrasMouseMoved(evt);
            }
        });
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAtrasMouseExited(evt);
            }
        });
        jPanel1.add(lblAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReglas.setBackground(new java.awt.Color(255, 255, 255));
        btnReglas.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnReglas.setForeground(new java.awt.Color(0, 153, 153));
        btnReglas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReglas.setText("Reglas");
        btnReglas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        btnReglas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReglas.setOpaque(true);
        btnReglas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnReglasMouseMoved(evt);
            }
        });
        btnReglas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReglasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReglasMouseExited(evt);
            }
        });
        jPanel2.add(btnReglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 140, 30));

        jScrollPane1.setBorder(null);

        jEditorPane1.setEditable(false);
        jEditorPane1.setBorder(null);
        jEditorPane1.setContentType("text/html"); // NOI18N
        jEditorPane1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jEditorPane1.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p align=\"center\">Este programa es un analizador léxico generado automáticamente con JFlex mediante un archivo con las reglas de configuración. Para ver el archivo pulsa el botón <b>\"Reglas\"</b>. Este analizador reconoce true, false, and, or, not, si, sii (si y sólo si) y <b>(</b> , <b>)</b>. Es decir, reconoce ecuaciones booleanas.</p>\r\n    <p align=\"left\">La configuración se cargará mediante el archivo <b>\"Reglas.jflex\"</b> que se encuentra en la carpeta <b>\"JFlex 2\"</b>.</p>\n    <p align=\"left\">Este programa analizará el archivo fuente en formato txt, que por defecto es el archivo <b>Fuente.txt</b> que se envuentra en la carpeta mencionada anteriormente. Si se desea utilizar otro archivo puede seleccionarse con el botón <b>\"Seleccionar archivo\"</b>.</p>\n    <p align=\"left\">Una vez que el archivo fuente esté seleccionado se pueden analizar las cadenas que se encuentren dentro de este con el botón <b>\"Analizar\".</b></p>\n  </body>\r\n</html>");
        jEditorPane1.setFocusable(false);
        jScrollPane1.setViewportView(jEditorPane1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 530, 280));

        btnSeleccionar.setBackground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(0, 153, 153));
        btnSeleccionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSeleccionar.setText("Seleccionar archivo fuente");
        btnSeleccionar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        btnSeleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionar.setOpaque(true);
        btnSeleccionar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSeleccionarMouseMoved(evt);
            }
        });
        btnSeleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSeleccionarMouseExited(evt);
            }
        });
        jPanel2.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 170, 30));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setText("Archivo fuente:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 20));

        txtRuta.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jPanel2.add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 440, -1));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 153, 153));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setText("Analizar");
        btnBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setOpaque(true);
        btnBuscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBuscarMouseMoved(evt);
            }
        });
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 80, 30));

        btnVerFuente.setBackground(new java.awt.Color(255, 255, 255));
        btnVerFuente.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnVerFuente.setForeground(new java.awt.Color(0, 153, 153));
        btnVerFuente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVerFuente.setText("Ver archivo fuente");
        btnVerFuente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        btnVerFuente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerFuente.setOpaque(true);
        btnVerFuente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnVerFuenteMouseMoved(evt);
            }
        });
        btnVerFuente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerFuenteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerFuenteMouseExited(evt);
            }
        });
        jPanel2.add(btnVerFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 120, 30));

        taSalida.setEditable(false);
        taSalida.setColumns(20);
        taSalida.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        taSalida.setRows(5);
        jScrollPane2.setViewportView(taSalida);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 290, 100));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel3.setText("Salida del analizador léxico:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 560, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseMoved
        lblCerrar.setBackground(Color.red);
    }//GEN-LAST:event_lblCerrarMouseMoved

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        lblCerrar.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_lblCerrarMouseExited

    private void lblMinimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseMoved
        lblMinimizar.setBackground(Color.blue);
    }//GEN-LAST:event_lblMinimizarMouseMoved

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseExited
        lblMinimizar.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_lblMinimizarMouseExited

    private void lblAtrasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseMoved
        lblAtras.setBackground(Color.blue);
    }//GEN-LAST:event_lblAtrasMouseMoved

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        ventanaSeleccion.setState(NORMAL);
        this.dispose();
    }//GEN-LAST:event_lblAtrasMouseClicked

    private void lblAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseExited
        lblAtras.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_lblAtrasMouseExited

    private void btnReglasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReglasMouseMoved
        btnReglas.setBackground(new Color(0, 153, 153));
        btnReglas.setForeground(Color.white);
    }//GEN-LAST:event_btnReglasMouseMoved

    private void btnReglasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReglasMouseClicked
        try {
            Runtime rt = Runtime.getRuntime();
            rt.exec("notepad " + System.getProperty("user.dir") + "\\JFlex 2\\Reglas.jflex");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al abrir el archivo. Si el error continua intenta abrirlo"
                + " manualmente desde la carpeta \"JFlex 2\"");
        }
    }//GEN-LAST:event_btnReglasMouseClicked

    private void btnReglasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReglasMouseExited
        btnReglas.setBackground(Color.white);
        btnReglas.setForeground(new Color(0, 153, 153));
    }//GEN-LAST:event_btnReglasMouseExited

    private void btnSeleccionarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarMouseMoved
        btnSeleccionar.setBackground(new Color(0, 153, 153));
        btnSeleccionar.setForeground(Color.white);
    }//GEN-LAST:event_btnSeleccionarMouseMoved

    private void btnSeleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarMouseClicked
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de texto", "txt");
        fc.setFileFilter(filtro);

        int seleccion = fc.showOpenDialog(this.getContentPane());

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            archivo = fc.getSelectedFile();
            txtRuta.setText(archivo.getAbsolutePath());
        } else if (seleccion == JFileChooser.ERROR_OPTION) {
            JOptionPane.showMessageDialog(null, "Error al abrir el archivo. Inténtalo de nuevo.");
        }
    }//GEN-LAST:event_btnSeleccionarMouseClicked

    private void btnSeleccionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarMouseExited
        btnSeleccionar.setBackground(Color.white);
        btnSeleccionar.setForeground(new Color(0, 153, 153));
    }//GEN-LAST:event_btnSeleccionarMouseExited

    private void btnBuscarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseMoved
        btnBuscar.setBackground(new Color(0, 153, 153));
        btnBuscar.setForeground(Color.white);
    }//GEN-LAST:event_btnBuscarMouseMoved

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        try {
            analizar();
        } catch(Exception e ){
            JOptionPane.showMessageDialog(null, "Error al analizar el archivo. Asegurate que sea un archivo fuente.");
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setBackground(Color.white);
        btnBuscar.setForeground(new Color(0, 153, 153));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnVerFuenteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerFuenteMouseMoved
        btnVerFuente.setBackground(new Color(0, 153, 153));
        btnVerFuente.setForeground(Color.white);
    }//GEN-LAST:event_btnVerFuenteMouseMoved

    private void btnVerFuenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerFuenteMouseClicked
        try {
            Runtime rt = Runtime.getRuntime();
            rt.exec("notepad " + archivo.getAbsolutePath());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al abrir el archivo. Si el error continua intenta abrirlo"
                + " manualmente desde la carpeta \"JFlex 2\"");
        }
    }//GEN-LAST:event_btnVerFuenteMouseClicked

    private void btnVerFuenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerFuenteMouseExited
        btnVerFuente.setBackground(Color.white);
        btnVerFuente.setForeground(new Color(0, 153, 153));
    }//GEN-LAST:event_btnVerFuenteMouseExited

    private void analizar() throws FileNotFoundException, IOException {
        this.taSalida.selectAll();
        this.taSalida.replaceSelection("");
        
        Reader reader = new BufferedReader(new FileReader(archivo));
        Lexico lexico = new Lexico(reader);
        String resultado = "";
        
        while(true) {
            Tokens token = lexico.yylex();
            
            if(token == null) {
                taSalida.append(resultado);
                return;
            }
            
            switch(token) {
            
                case TRUE:
                    resultado = resultado + "<true>";
                    break;
                    
                case FALSE:
                    resultado = resultado + "<false>";
                    break;
                    
                case AND:
                    resultado = resultado + "<and>";
                    break;
                    
                case OR:
                    resultado = resultado + "<or>";
                    break;
                    
                case NOT:
                    resultado = resultado + "<not>";
                    break;
                    
                case SII:
                    resultado = resultado + "<sii>";
                    break;
                    
                case SI:
                    resultado = resultado + "<si>";
                    break;   
        
                case PARAP:
                    resultado = resultado + "<paren izq>";
                    break;
                    
                case PARCI:
                    resultado = resultado + "<paren der>";
                    break;
                    
                case ERROR:
                default:
                    resultado = resultado + "Error, símbolo <" + lexico.yytext() + "> no reconocido";
            }
            
            resultado += "\n";
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFlex2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFlex2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFlex2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFlex2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFlex2(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnReglas;
    private javax.swing.JLabel btnSeleccionar;
    private javax.swing.JLabel btnVerFuente;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JTextArea taSalida;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
