/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fes.aragon.programas;

import AppPackage.AnimationClass;
import fes.aragon.Seleccion;
import fes.aragon.archivos.asint6.Lexico;
import fes.aragon.archivos.asint6.Token;
import fes.aragon.archivos.asint6.Tokens;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Axel
 */
public class Sintactico6 extends javax.swing.JFrame {
    private Seleccion ventanaSeleccion;
    
    private File archivo;
    private List<Token> tokensLista;
    private int contadorToken = 0;
    private Token tokens;
    private String resultadoSintactico = "";
    private boolean error = false;
    private boolean errorLexico = false;
    
    /**
     * Creates new form Sintactico6
     */
    public Sintactico6(Seleccion ventanaAnterior) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.ventanaSeleccion = ventanaAnterior;
        txtRuta.setText(System.getProperty("user.dir") + "\\Sintactico6\\Fuente.txt");
        archivo = new File(txtRuta.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAtras = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnReglas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        btnSeleccionar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRuta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        btnVerFuente = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taSalida = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taSintactico = new javax.swing.JTextArea();
        lblIncorrecto = new javax.swing.JLabel();
        lblCorrecto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrar.setBackground(new java.awt.Color(0, 153, 153));
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fes/aragon/imagenes/Cerrar.png"))); // NOI18N
        lblCerrar.setToolTipText("Cerrar");
        lblCerrar.setOpaque(true);
        lblCerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCerrarMouseMoved(evt);
            }
        });
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarMouseExited(evt);
            }
        });
        jPanel1.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        lblMinimizar.setBackground(new java.awt.Color(0, 153, 153));
        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fes/aragon/imagenes/Minimizar.png"))); // NOI18N
        lblMinimizar.setToolTipText("Minimizar");
        lblMinimizar.setOpaque(true);
        lblMinimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseMoved(evt);
            }
        });
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseExited(evt);
            }
        });
        jPanel1.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel5.setText("Programa 13: Sintáctico 6");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, 20));

        lblAtras.setBackground(new java.awt.Color(0, 153, 153));
        lblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fes/aragon/imagenes/atras.png"))); // NOI18N
        lblAtras.setToolTipText("Atrás");
        lblAtras.setOpaque(true);
        lblAtras.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblAtrasMouseMoved(evt);
            }
        });
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAtrasMouseExited(evt);
            }
        });
        jPanel1.add(lblAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReglas.setBackground(new java.awt.Color(255, 255, 255));
        btnReglas.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnReglas.setForeground(new java.awt.Color(0, 153, 153));
        btnReglas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReglas.setText("Diagrama");
        btnReglas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        btnReglas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReglas.setOpaque(true);
        btnReglas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnReglasMouseMoved(evt);
            }
        });
        btnReglas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReglasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReglasMouseExited(evt);
            }
        });
        jPanel2.add(btnReglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 140, 30));

        jScrollPane1.setBorder(null);

        jEditorPane1.setEditable(false);
        jEditorPane1.setBorder(null);
        jEditorPane1.setContentType("text/html"); // NOI18N
        jEditorPane1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jEditorPane1.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p align=\"center\">Este programa es un analizador sintáctico que analiza cadenas de acuerdo al diagrama que puede verse pulsando el botón <b>\"Diagrama\"</b></p>\r\n    <p align=\"left\">Este programa analizará el archivo fuente en formato txt, que por defecto es el archivo <b>Fuente.txt</b> que se envuentra en la carpeta mencionada anteriormente. Si se desea utilizar otro archivo puede seleccionarse con el botón <b>\"Seleccionar archivo\"</b>.</p>\n    <p align=\"left\">Una vez que el archivo fuente esté seleccionado se pueden analizar las cadenas que se encuentren dentro de este con el botón <b>\"Analizar\".</b></p>\n  </body>\r\n</html>");
        jEditorPane1.setFocusable(false);
        jScrollPane1.setViewportView(jEditorPane1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 530, 220));

        btnSeleccionar.setBackground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(0, 153, 153));
        btnSeleccionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSeleccionar.setText("Seleccionar archivo fuente");
        btnSeleccionar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        btnSeleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionar.setOpaque(true);
        btnSeleccionar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSeleccionarMouseMoved(evt);
            }
        });
        btnSeleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSeleccionarMouseExited(evt);
            }
        });
        jPanel2.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 170, 30));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setText("Archivo fuente:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 20));

        txtRuta.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jPanel2.add(txtRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 440, -1));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 153, 153));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setText("Analizar");
        btnBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setOpaque(true);
        btnBuscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBuscarMouseMoved(evt);
            }
        });
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 80, 30));

        btnVerFuente.setBackground(new java.awt.Color(255, 255, 255));
        btnVerFuente.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnVerFuente.setForeground(new java.awt.Color(0, 153, 153));
        btnVerFuente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVerFuente.setText("Ver archivo fuente");
        btnVerFuente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 2, true));
        btnVerFuente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerFuente.setOpaque(true);
        btnVerFuente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnVerFuenteMouseMoved(evt);
            }
        });
        btnVerFuente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerFuenteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerFuenteMouseExited(evt);
            }
        });
        jPanel2.add(btnVerFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 120, 30));

        taSalida.setEditable(false);
        taSalida.setColumns(20);
        taSalida.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        taSalida.setRows(5);
        jScrollPane2.setViewportView(taSalida);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 410, 80));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel3.setText("Salida sintáctico:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setText("Salida léxico:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jScrollPane3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        taSintactico.setColumns(20);
        taSintactico.setRows(5);
        jScrollPane3.setViewportView(taSintactico);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 410, 80));

        lblIncorrecto.setBackground(new java.awt.Color(255, 255, 255));
        lblIncorrecto.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblIncorrecto.setForeground(new java.awt.Color(192, 57, 43));
        lblIncorrecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fes/aragon/imagenes/incorrecto.png"))); // NOI18N
        lblIncorrecto.setText("¡Incorrecto!");
        jPanel2.add(lblIncorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, -1, -1));

        lblCorrecto.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblCorrecto.setForeground(new java.awt.Color(39, 174, 96));
        lblCorrecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fes/aragon/imagenes/correcto.png"))); // NOI18N
        lblCorrecto.setText("¡Correcto!");
        jPanel2.add(lblCorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, 100, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 560, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseMoved
        lblCerrar.setBackground(Color.red);
    }//GEN-LAST:event_lblCerrarMouseMoved

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseExited
        lblCerrar.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_lblCerrarMouseExited

    private void lblMinimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseMoved
        lblMinimizar.setBackground(Color.blue);
    }//GEN-LAST:event_lblMinimizarMouseMoved

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseExited
        lblMinimizar.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_lblMinimizarMouseExited

    private void lblAtrasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseMoved
        lblAtras.setBackground(Color.blue);
    }//GEN-LAST:event_lblAtrasMouseMoved

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        ventanaSeleccion.setState(NORMAL);
        this.dispose();
    }//GEN-LAST:event_lblAtrasMouseClicked

    private void lblAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseExited
        lblAtras.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_lblAtrasMouseExited

    private void btnReglasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReglasMouseMoved
        btnReglas.setBackground(new Color(0, 153, 153));
        btnReglas.setForeground(Color.white);
    }//GEN-LAST:event_btnReglasMouseMoved

    private void btnReglasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReglasMouseClicked
        try {
            Runtime rt = Runtime.getRuntime();
            rt.exec("cmd /c start " + System.getProperty("user.dir") + "\\Sintactico6\\Diagrama.docx");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al abrir el archivo. Si el error continua intenta abrirlo"
                + " manualmente desde la carpeta \"Sintactico6\"");
        }
    }//GEN-LAST:event_btnReglasMouseClicked

    private void btnReglasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReglasMouseExited
        btnReglas.setBackground(Color.white);
        btnReglas.setForeground(new Color(0, 153, 153));
    }//GEN-LAST:event_btnReglasMouseExited

    private void btnSeleccionarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarMouseMoved
        btnSeleccionar.setBackground(new Color(0, 153, 153));
        btnSeleccionar.setForeground(Color.white);
    }//GEN-LAST:event_btnSeleccionarMouseMoved

    private void btnSeleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarMouseClicked
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de texto", "txt");
        fc.setFileFilter(filtro);

        int seleccion = fc.showOpenDialog(this.getContentPane());

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            archivo = fc.getSelectedFile();
            txtRuta.setText(archivo.getAbsolutePath());
        } else if (seleccion == JFileChooser.ERROR_OPTION) {
            JOptionPane.showMessageDialog(null, "Error al abrir el archivo. Inténtalo de nuevo.");
        }
    }//GEN-LAST:event_btnSeleccionarMouseClicked

    private void btnSeleccionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarMouseExited
        btnSeleccionar.setBackground(Color.white);
        btnSeleccionar.setForeground(new Color(0, 153, 153));
    }//GEN-LAST:event_btnSeleccionarMouseExited

    private void btnBuscarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseMoved
        btnBuscar.setBackground(new Color(0, 153, 153));
        btnBuscar.setForeground(Color.white);
    }//GEN-LAST:event_btnBuscarMouseMoved

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        lblCorrecto.setLocation(240, 600);
        lblIncorrecto.setLocation(240, 600);
        error = false;
        errorLexico = false;
        tokens = null;
        taSalida.setText("");
        taSintactico.setText("");
        tokensLista = new LinkedList<Token>();
        resultadoSintactico = "";
        contadorToken = 0;
        
        try {
            analizar();
            
            if (!error && !errorLexico) {
                AnimationClass anim = new AnimationClass();
                anim.jLabelYUp(600, 540, 10, 5, lblCorrecto);
            } else {
                AnimationClass anim = new AnimationClass();
                anim.jLabelYUp(600, 540, 10, 5, lblIncorrecto);
            }
        } catch(Exception e ){
            JOptionPane.showMessageDialog(null, "Error al analizar el archivo. Asegurate que sea un archivo fuente.");
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setBackground(Color.white);
        btnBuscar.setForeground(new Color(0, 153, 153));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnVerFuenteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerFuenteMouseMoved
        btnVerFuente.setBackground(new Color(0, 153, 153));
        btnVerFuente.setForeground(Color.white);
    }//GEN-LAST:event_btnVerFuenteMouseMoved

    private void btnVerFuenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerFuenteMouseClicked
        try {
            Runtime rt = Runtime.getRuntime();
            rt.exec("notepad " + archivo.getAbsolutePath());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error al abrir el archivo. Si el error continua intenta abrirlo"
                + " manualmente desde la carpeta \"Sintactico6\"");
        }
    }//GEN-LAST:event_btnVerFuenteMouseClicked

    private void btnVerFuenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerFuenteMouseExited
        btnVerFuente.setBackground(Color.white);
        btnVerFuente.setForeground(new Color(0, 153, 153));
    }//GEN-LAST:event_btnVerFuenteMouseExited

    private void analizar() {
        try {
            analisisLexico();
            secuencia();
            
            taSintactico.append(resultadoSintactico);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
    
    public void analisisLexico() throws FileNotFoundException, IOException {

        tokensLista = new LinkedList<>();
        this.taSintactico.selectAll();
        this.taSintactico.replaceSelection("");
        int contadorID = 0;
        
        Reader reader = new BufferedReader(new FileReader(archivo));
        Lexico lexico = new Lexico(reader);
        String resultado = "";

        while (true) {
            Tokens token = lexico.yylex();
            
            if (token == null) {
                taSalida.append(resultado);
                return;
            }

            switch (token) {

                case MAS:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(10);
                    tokensLista.add(tokens);
                    resultado = resultado + "<+>";
                    break;
                    
                case MENOS:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(11);
                    tokensLista.add(tokens);
                    resultado = resultado + "<->";
                    break;
                    
                case IGUAL:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(4);
                    tokensLista.add(tokens);
                    resultado = resultado + "<=>";
                    break;
                    
                case ERROR:
                    tokens.setNombre(lexico.yytext());
                    tokens.setId(contadorID);
                    tokensLista.add(tokens);
                    resultado = resultado + "Error, simbolo " + lexico.yytext() + " no reconocido";
                    errorLexico = true;
                    break;
                    
                case ID:
                    contadorID++;
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setId(contadorID);
                    tokens.setTipo(1);
                    tokensLista.add(tokens);
                    resultado = resultado + "<ID" + contadorID + ">";
                    break;
                    
                case NUM:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(2);
                    tokensLista.add(tokens);
                    resultado = resultado + "<" + lexico.lexema + ">";
                    break;
                    
                case PUNTOYCOMA:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(3);
                    tokensLista.add(tokens);
                    resultado = resultado + "<;>";
                    break;
                    
                case ME:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(5);
                    tokensLista.add(tokens);
                    resultado = resultado + "<-<->";
                    break;
                    
                case MEI:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(6);
                    tokensLista.add(tokens);
                    resultado = resultado + "<-<=->";
                    break;
                    
                case DIST:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(7);
                    tokensLista.add(tokens);
                    resultado = resultado + "<!=>";
                    break;
                    
                case MAI:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(8);
                    tokensLista.add(tokens);
                    resultado = resultado + "<->=->";
                    break;
                    
                case MA:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(9);
                    tokensLista.add(tokens);
                    resultado = resultado + "<->->";
                    break;
                    
                case OR:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(12);
                    tokensLista.add(tokens);
                    resultado = resultado + "<or>";
                    break;
                    
                case POR:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(13);
                    tokensLista.add(tokens);
                    resultado = resultado + "<*>";
                    break;
                    
                case DIV:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(14);
                    tokensLista.add(tokens);
                    resultado = resultado + "</>";
                    break;
                    
                case DIV_ENT:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(15);
                    tokensLista.add(tokens);
                    resultado = resultado + "<div>";
                    break;
                    
                case MOD:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(16);
                    tokensLista.add(tokens);
                    resultado = resultado + "<mod>";
                    break;
                    
                case AND:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(17);
                    tokensLista.add(tokens);
                    resultado = resultado + "<and>";
                    break;
                    
                case NOT:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(18);
                    tokensLista.add(tokens);
                    resultado = resultado + "<not>";
                    break;
                    
                case AB_PARID:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(19);
                    tokensLista.add(tokens);
                    resultado = resultado + "<(>";
                    break;
                    
                case CE_PAR:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokens.setTipo(20);
                    tokensLista.add(tokens);
                    resultado = resultado + "<)>";
                    break;
                    
                default:
                    tokens = new Token();
                    tokens.setNombre(lexico.yytext());
                    tokensLista.add(tokens);
                    resultado = resultado + "<" + lexico.lexema + ">";
            }
        }
    }
    
    public Token getToken() {
        tokens = null;
        if (contadorToken < tokensLista.size()) {
            tokens = tokensLista.get(contadorToken++);
        }
        return tokens;
    }
    
    private void secuencia() {
        tokens = getToken();
        do {
            expresion();
            if(tokens != null ){
                while(tokens != null && tokens.getTipo() != 3) {
                    error = true;
                    tokens = getToken();
                }
            } else {
                error = true;
            }
            tokens = getToken();
        } while(tokens != null);
        
        if(!error) {
            taSintactico.append("Correcto");
        } else {
            taSintactico.append("Error de sintaxis");
        }
    }

    private void expresion() {
        if (tokens != null) {
            exprSimple();
            if (tokens != null && (tokens.getTipo() == 4 || tokens.getTipo() == 5 || 
                    tokens.getTipo() == 6 || tokens.getTipo() == 7 || 
                    tokens.getTipo() == 8 || tokens.getTipo() == 9)) {
                
                tokens = getToken();
                exprSimple();
            }
        } 
    }

    private void exprSimple() {
        if (tokens != null) {
            if (tokens.getTipo() == 10 || tokens.getTipo() == 11) {
                tokens = getToken();
              
            } else {
                termino();
            }
            while(tokens != null && (tokens.getTipo() == 10 || tokens.getTipo() == 11 || 
                    tokens.getTipo() == 12)) {
                
                tokens = getToken();
                termino();
            }
        }
    }

    private void termino() {
        if (tokens != null) {
            factor();
            if (tokens != null) {
                while(tokens.getTipo() == 13 || tokens.getTipo() == 14 || tokens.getTipo() == 15
                        || tokens.getTipo() == 16 || tokens.getTipo() == 17) {
                    
                    tokens = getToken();
                    factor();
                }
            }
        }
    }

    private void factor() {
        if (tokens != null) {
            switch (tokens.getTipo()) {
                
                case 1:
                    tokens = getToken();
                    break;
                    
                case 2:
                    tokens = getToken();
                    break;
                    
                case 18:
                    tokens = getToken();
                    if (tokens != null) {
                        factor();
                    }
                    break;
                    
                case 19:
                    tokens = getToken();
                    if (tokens != null) {
                        expresion();
                        if (tokens == null || tokens.getTipo() != 20 ) {
                            error = true;
                        } else {
                            tokens = getToken();
                        }
                    } else {
                        error = true;
                    }
                    break;
                    
                default:
                    error = true;
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sintactico6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sintactico6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sintactico6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sintactico6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sintactico6(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnReglas;
    private javax.swing.JLabel btnSeleccionar;
    private javax.swing.JLabel btnVerFuente;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblCorrecto;
    private javax.swing.JLabel lblIncorrecto;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JTextArea taSalida;
    private javax.swing.JTextArea taSintactico;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
